name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: Flutterをセットアップ
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: パッケージをインストール
        run: flutter pub get

      - name: Web用にビルド
        run: flutter build web --base-href "/remory/"

      - name: GitHub Pagesにデプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web